apiVersion: v1
data:
    Pass: ENC[AES256_GCM,data:XoqoMtgupQM=,iv:ot4xSytX6DbBSSO6jW9VZqfJ/HW8q4QpjRixVZr4wl0=,tag:Ijjm3i6no/pGOH0LUnymgw==,type:str]
    User: ENC[AES256_GCM,data:j4Cfjj01tls=,iv:4XY3PfQ94PKlsIcHMMKhUxPIW4SXGLVBXs6aMCv+pN8=,tag:oCDYVOXWhAWyFZX+MrwMTw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-argo-bbb
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-25T10:02:41Z"
    mac: ENC[AES256_GCM,data:BQcjvYUkF8xsW/qf7yWiJQV2bXsgT+rXUD0URBULNEfvy6vKLp15GJTvDIWN1fbb4/H6FISXgNHwU+JWFClqWADt7ZPlMycP9i2y2Dyv7iWRhxW8nm7Pk4mGfHK5aB7Dif0pC2ewNnQmDm7IhJNXs65TdfTqYmy+1hHPjcwLgAY=,iv:2WXtR9057nTrInsmn4ASAqHAy6iuUHPrBb2aWdsqDqU=,tag:jTBj0GA6tvZq9DXbTfwI4w==,type:str]
    pgp:
        - created_at: "2024-01-25T10:02:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAyUpShfNkFB/AQf/ZmOGzoXgtlOciPg00xkxFBfqTBrPkXLKNEPWGNNZSgUR
            ucp1kUKUWQR9IHTRXQMPnxEntkRfCqmpdaSNNaJjCbYvWQ17RszdK1PfYFW4UzP4
            pO+rYxLuUnwthgsWs3+sONdq+M/5gCnIhZb4F3rmyItHzxWQnbUmRMs02pI7eLTy
            vIlkx7uHZVAPpp7MWcYxOYWvfn+y3u1JQ3NctKJWiot4fjJDzodtw6d04TYZIpcF
            lonNygXtbJ9ReFI1fCM9Jzj2pzNYSKbx+6qmL17CqnqBBbI+H+RePbcTNHI+g+SY
            KjTEq9b5KX4aQ86GwenQ5KgjGXX0JPZhrRa8x99F89JcAbJqRrutambHK1NL0BPi
            RbTsF1QZT1XzUEZIDXF7kXQ3MXQ1M2EyqbSGY0ugPMwhsu3lIDPCo/zCmrexybdK
            7I1hFFgbSX9z4nqw4xUteiMKIjEanIUyaQ1fXVY=
            =bHJP
            -----END PGP MESSAGE-----
          fp: FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
